"""core.comic.env_snapshot — the ``h_env`` digest for content-addressed keys.

``h_env`` covers everything that changes generated bytes while living outside
the Python source: the resolved font's *bytes*, the resolved output size, the
provider identity, and the registered output-affecting switches. Python source
identity is a separate component (``h_stage``), so it is not repeated here.

Three rules from §5 shape this module:

1. Values are the **resolved** ones, never config strings. A font path can
   resolve to different bytes on different machines; a requested size can
   silently fall back to a smaller one (§8 invariant 6b).
2. Runtime-only knobs (concurrency, throttling, retries, deadlines, log paths)
   never enter. They cannot change bytes, and folding them in causes
   over-invalidation, which is itself a defect.
3. Credentials never enter. Rotating a key must not invalidate cached work, and
   a key must never be reconstructible from a digest's inputs.

The registry below is asserted to partition ``core.config.ALL_ENV_VARS``
exactly, so adding an output-affecting switch without registering it fails a
test rather than silently missing every key.
"""

import hashlib
import json

from core.comic.fonts import resolved_font_digest
from core.config import (
    ENV_AGNES_API_KEY,
    ENV_AGNES_CHAT_MODEL,
    ENV_AGNES_IMAGE_2K_RPM,
    ENV_AGNES_IMAGE_3K_RPM,
    ENV_AGNES_IMAGE_I2I_MODEL,
    ENV_AGNES_IMAGE_MAX_RETRIES,
    ENV_AGNES_IMAGE_RETRY_BASE_DELAY,
    ENV_AGNES_RATE_LIMIT,
    ENV_ERROR_LOG,
    ENV_FONT_PATH,
    ENV_INKSTONE_IMAGE_CONCURRENCY,
    ENV_INKSTONE_PANEL_CONTINUITY,
    ENV_L3,
    ENV_OPENAI_COMPAT_API_KEY,
    ENV_OPENAI_COMPAT_BASE_URL,
    ENV_OPENAI_COMPAT_CHAT_API_KEY,
    ENV_OPENAI_COMPAT_CHAT_BASE_URL,
    ENV_OPENAI_COMPAT_CHAT_MODEL,
    ENV_OPENAI_COMPAT_MODEL_I2I,
    ENV_OPENAI_COMPAT_MODEL_T2I,
    ENV_PAGE_SCRIPT,
    ENV_PAGE_SIZE,
    ENV_PROVIDER,
    ENV_RENDER_MODE,
    ENV_RUN_DEADLINE_HOURS,
    ENV_SUPERVISOR_BACKOFF_BASE,
    ENV_SUPERVISOR_BACKOFF_CAP,
    ENV_WEBTOON_MAX_PIXELS,
    ENV_WEBTOON_WARN_MB,
    ChatConfig,
    ImageConfig,
    finished_page_size,
    l3_enabled,
    page_script_enabled,
    render_mode,
)

# Switches whose value can change generated bytes, so they belong in the digest.
# INKSTONE_FONT_PATH is deliberately absent: its *path string* is not identity,
# while the bytes it resolves to enter through resolved_font_digest().
H_ENV_REGISTERED: frozenset[str] = frozenset(
    {
        ENV_L3,
        ENV_PAGE_SIZE,
        ENV_PAGE_SCRIPT,
        ENV_RENDER_MODE,
        ENV_PROVIDER,
        ENV_INKSTONE_PANEL_CONTINUITY,
        ENV_AGNES_IMAGE_I2I_MODEL,
        ENV_AGNES_CHAT_MODEL,
        ENV_OPENAI_COMPAT_BASE_URL,
        ENV_OPENAI_COMPAT_MODEL_T2I,
        ENV_OPENAI_COMPAT_MODEL_I2I,
        ENV_OPENAI_COMPAT_CHAT_BASE_URL,
        ENV_OPENAI_COMPAT_CHAT_MODEL,
    }
)

# Switches that provably cannot change bytes: throttling, concurrency, retry
# policy, deadlines, log destinations, capacity warnings, credentials. Retry
# exhaustion is recorded as an ``outcome`` (§6), never as part of a key.
H_ENV_EXCLUDED: frozenset[str] = frozenset(
    {
        ENV_FONT_PATH,
        ENV_INKSTONE_IMAGE_CONCURRENCY,
        ENV_AGNES_RATE_LIMIT,
        ENV_AGNES_IMAGE_2K_RPM,
        ENV_AGNES_IMAGE_3K_RPM,
        ENV_AGNES_IMAGE_MAX_RETRIES,
        ENV_AGNES_IMAGE_RETRY_BASE_DELAY,
        ENV_RUN_DEADLINE_HOURS,
        ENV_SUPERVISOR_BACKOFF_BASE,
        ENV_SUPERVISOR_BACKOFF_CAP,
        ENV_WEBTOON_WARN_MB,
        ENV_WEBTOON_MAX_PIXELS,
        ENV_ERROR_LOG,
        ENV_AGNES_API_KEY,
        ENV_OPENAI_COMPAT_API_KEY,
        ENV_OPENAI_COMPAT_CHAT_API_KEY,
    }
)


def h_env(
    *,
    text: str,
    resolved_size: str | None = None,
    font_path: str | None = None,
) -> str:
    """Return the SHA-256 of every byte-affecting value outside the source.

    Args:
        text: the text whose font resolution determines the font digest. Callers
            pass the text that will actually be drawn on the artifact under key.
        resolved_size: the size the call will really use. Pass the fallback
            (``1024x1024``) when a size error triggered one, so the key reflects
            the bytes rather than the request (§8 invariant 6b). ``None`` means
            no fallback occurred and the configured size is authoritative.
        font_path: an explicit per-engine font override, mirroring
            ``fonts.resolve_font``.

    Returns:
        A 64-character lowercase hex digest. Two calls with equal
        bytes-affecting inputs return the same digest; any difference in the
        registered set, the resolved font bytes, or the resolved size changes it.
    """
    image = ImageConfig()
    chat = ChatConfig()
    payload = {
        "font_digest": resolved_font_digest(text, font_path=font_path),
        "resolved_size": resolved_size or finished_page_size(),
        "render_mode": render_mode(),
        "provider": image.provider,
        "image_i2i_model": image.agnes_i2i_model,
        "chat_model": chat.agnes_chat_model,
        "openai_base_url": image.openai_compat_base_url,
        "openai_t2i_model": image.openai_compat_model_t2i,
        "openai_i2i_model": image.openai_compat_model_i2i,
        "openai_chat_base_url": chat.openai_compat_chat_base_url,
        "openai_chat_model": chat.openai_compat_chat_model,
        "l3_enabled": l3_enabled(),
        "panel_continuity": image.panel_continuity,
        "page_script_enabled": page_script_enabled(),
    }
    canonical = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
